### ISSUE TITLE
Template:Settings Quality Quality Table Meanings

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#116]
Created this template as all 4 ARRs had the same information just needed a variable or two to make it work easily
Variables
*{{{BITRATET1}}}
*Megabytes per Minute (MB/min)
*Kilobitets per second (KB/s)
*{{{BITRATE2}}}
*Megabytes Per Minute
*Kilobytes Per Second

**Comment by bakerboy448** [comment]
Edits made; templatedata created
