### ISSUE TITLE
Template:Settings Indexers Indexers

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#120]
https://wiki.servarr.com/Template:Settings_Indexers_Indexers
Still need to add variables template

**Comment by bakerboy448** [comment]
isn't this under settings_indexers; can close and remove from project/milestone?

**Comment by Drazzilb08** [comment]
@bakerboy448 This is the template for the subsection of Indexers under the Indexers main section. This will also include the pop up window that allows you to set your indexers as well.
I feel this will be a good template as the settings and setting up of the indexers will be the same across ARRs
