### ISSUE TITLE
Template:Settings Indexers Options

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#121]
https://wiki.servarr.com/Template:Settings_Indexers_Options
Still need to add template variables

**Comment by bakerboy448** [comment]
@Drazzilb08 review

incorporated https://github.com/Sonarr/Sonarr/wiki/RSS-Sync

**Comment by Drazzilb08** [comment]
Also need to be mindful of header indention with headers example of this was == RSS Sync == needs to have been ===== RSS Sync ===== to make it fit right on the main page. 

Corrections already made still ready for review

**Comment by bakerboy448** [comment]
looks good
