### ISSUE TITLE
Consolidated Profiles Page

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#124]
https://wiki.servarr.com/Settings_Profiles

Created a consolidated Profilest page where all edits can be made in regards to media management across all ARRs. 

Every section is labeled and `sections` are transcoded to ARR specific settings page

This will allow for reorganizing and putting the Settings wiki in the same order as it appears on the application. This will also allow for restructuring or moving around entire sections with ease.

**Comment by bakerboy448** [comment]
fix the links; otherwise content looks good
