### ISSUE TITLE
Consolidated Custom Formats Page

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#125]
https://wiki.servarr.com/Settings_Custom_Formats

At the time of writing this Radarr is the only ARR with custom formats `if` one of the Devs decide to implement it into the other ARRs this will be the page to edit across all the ARRs

Created a consolidated Custom Formats page where all edits can be made in regards to media management across all ARRs. 

Every section is labeled and `sections` are transcoded to ARR specific settings page

This will allow for reorganizing and putting the Settings wiki in the same order as it appears on the application. This will also allow for restructuring or moving around entire sections with ease.

**Comment by bakerboy448** [comment]
done. closing
