### ISSUE TITLE
Servarr Icon

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#132]
Combine all 4 Arrs into one icon

**Comment by flying-sausages** [comment]
I'd much rather have a new icon which follows the original "ideology" of the -arr icons, but does its own thing to show its "over-archingness"

**Comment by Drazzilb08** [comment]
> I'd much rather have a new icon which follows the original "ideology" of the original -arr icons, but does its own thing to show its "over-archingness"

I think maybe we see what both would look like and go from there?

**Comment by Drazzilb08** [comment]
This issue is closed as we have found branding that works. Always open to new ideas though.
