### ISSUE TITLE
Links not working in Wiki

### ISSUE THREAD

**Issue by n0rd1c** [Servarr/Wiki#135]
https://wiki.servarr.com/Lidarr_System#update_to_net_core_version

When I click on the links to download the correct build for my architecture (in this case, x64) the link takes me to a page (https://lidarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64) and this is what is posted:

{"errorMessage":"Update file for master- not found."}

**Comment by bakerboy448** [comment]
Swap `master` for `develop`

No plans to update it at this point as lidarr v0.8 should be hitting master soon enough
