### ISSUE TITLE
Convert to WikiJS

### ISSUE THREAD

**Issue by Qstick** [Servarr/Wiki#138]
Issue to track conversion to wiki.js

- [x] Deploy test instance
- [ ] Permission Groups
  - [x] Setup Mod Group
  - [ ] Decide who can Write and Upload Images (Contributors group? Or all)
- [x] Setup
  - [x] Logo
  - [x] Favicon (docker compose edit)
  - [x] General Settings
- [ ] Auth
  - [x] Github
  - [ ] Discord?
  - [ ] Google?
- [x] Analytics
  - [x] Add to Google
- [x] Storage/Backup
  - [x] Git Backup
- [ ] Migration of Data

**Comment by bakerboy448** [comment]
Wiki.js finally implement templates + template & section transclusion?

**Comment by Qstick** [comment]
Nope

**Comment by ta264** [comment]
To be honest I'm not sold on the benefits of transclusion if that means mediawiki... It just ends up that no one else will touch it

**Comment by bakerboy448** [comment]
True.  100% agree that the wiki needs more contributions!

Wiki.js does have it marked as in progress, so it's coming at some point.

**Comment by Qstick** [comment]
Closing, we can manage issues that come up
