### ISSUE TITLE
auto copy link via header overlay

### ISSUE THREAD

**Issue by thezoggy** [Servarr/Wiki#156]
right now if you want to share a link you have to manually right click the anchor over to put to clipboard. many other sites auto put it to clipboard by clicking on the header overlay. 

[AB#1164](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1164)

**Comment by Qstick** [comment]
This seems like a issue wikijs FR, and not anything necessarily that we can fix

**Comment by thezoggy** [comment]
bakerboy asked me to create it here

**Comment by bakerboy448** [comment]
Not sure if we can do any customization for it or not; either way good to note
