### ISSUE TITLE
/readarr/library don't exist

### ISSUE THREAD

**Issue by blazejkapala** [Servarr/Wiki#164]
https://wiki.servarr.com/readarr/library
Don't exist or help need to write about it?

[AB#2120](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2120)

**Comment by bakerboy448** [comment]
It does 

https://github.com/Servarr/Wiki/blob/master/readarr/library.md

But wikijs likes to randomly forget files exist and unfortunately I don't have the permissions to trigger a force sync

**Comment by blazejkapala** [comment]
OK
