### ISSUE TITLE
Feature - add Bazarr to wiki

### ISSUE THREAD

**Issue by dicolanl** [Servarr/Wiki#176]
bring bazarr into the fold![
](https://github.com/morpheus65535/bazarr)

[AB#3006](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3006)

**Comment by bakerboy448** [comment]
No plans.

bazarr is a separate completely independent app that is \*arr in name only.  They can create and host their own wiki and likely already do.
