### ISSUE TITLE
Can't get Radarr to install using the ArrInstall.sh script

### ISSUE THREAD

**Issue by Harry-Harrison** [Servarr/Wiki#184]
I did have this working once, but stupidly clicked update within the app and now it doesn't load. So I thought I'd trying re-installing it using this same script and now when I run through the steps I get this in the terminal.

```
Saving to: ‘Radarr.master.4.2.4.6635.linux-core-arm.tar.gz.2’

Radarr.master.4.2.4.6635. 100%[===================================>]  88.75M  9.54MB/s    in 9.9s    

2022-10-15 12:24:52 (8.94 MB/s) - ‘Radarr.master.4.2.4.6635.linux-core-arm.tar.gz.2’ saved [93062345/93062345]

tar: Radarr.master.4.2.4.6635.linux-core-arm.tar.gz: Not found in archive
tar: Exiting with failure status due to previous errors
```

I'm trying to install it on a Raspberry pi and I can see the file, but none of this actually means anything to me I'm afraid. Can someone help?

[AB#3906](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3906)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
