### ISSUE TITLE
Python Custom Script can't log INFO via stdout

### ISSUE THREAD

**Issue by dcampillo** [Servarr/Wiki#187]
With python custom scripts:

`sys.stderr.write("Information from the script")` will be written in the *arr log file as ERR, but 
`print("Information from the script")` or `sys.stdout.write("Information from the script")` are not written anywhere.

I don't know if this is related to Python, but this make challenging to log any successful action done via a Python script.

Python script reference: https://github.com/dcampillo/arr-unmonitor

**In the documentation, it is mentionned:**
**Radarr Logs**
Note that the following will only be logged for custom scripts:

Script stdout output will be logged as Debug
Script stderr output will be logged as Info
The trigger of the script will be logged in Trace

[AB#4006](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4006)

**Comment by bakerboy448** [comment]
The wiki is not for support.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
