### ISSUE TITLE
RARBG API issue?

### ISSUE THREAD

**Issue by quadcom** [Servarr/Wiki#188]
API is either down or needs an update.

Running custom build which may not be current
Mono Version: 6.12.0.122

[AB#4050](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4050)

**Comment by quadcom** [comment]
https://torrentapi.org/ returning 403. Could be server-side.

**Comment by bakerboy448** [comment]
Wiki GitHub issues are for wiki related items only.

please use the various support methods for the \*arr app
