### ISSUE TITLE
Additional data to delete when migrating Radarr's DB to Postgres

### ISSUE THREAD

**Issue by imjuzcy** [Servarr/Wiki#191]
In the instructions to migrate Radarr's sqlite DB to postgres, when making sure Radarr starts on the new postgres DB before migrating data, Radarr also writes to the tables "NamingConfig", "ScheduledTasks", and "VersionInfo".

The last two might now be that important, but "NamingConfig" is important to a lot of people if they have that set up. So the existing data in that table in the postgres DB should be cleared before migrating.

For the sake of completeness, I think all tables should be cleared before migrating, so the commands should be

```
DELETE FROM "Profiles";
DELETE FROM "QualityDefinitions";
DELETE FROM "DelayProfiles";
DELETE FROM "Metadata";
DELETE FROM "NamingConfig";
DELETE FROM "ScheduledTasks";
DELETE FROM "VersionInfo";
```

[AB#4310](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4310)

**Comment by bakerboy448** [comment]
There is no need nor reason to clear all tables

Please visit the discord if you have Postgres questions.
