### ISSUE TITLE
Lidarr will automatically migrate the data from sqlite to postgres

### ISSUE THREAD

**Issue by imjuzcy** [Servarr/Wiki#192]
After setting up the `config.xml` and starting Lidarr, it'll migrate the data by itself, so it's not necessary to do anything mentioned in the "Migrating data" subsection.

```
[Info] MigrationController: *** Migrating data source=/config/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
```

[AB#4311](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4311)

**Comment by bakerboy448** [comment]
The migration details noted in the wiki are required.

The migration you see in the logs is the internal db migration agnostic of PG/sql
