### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by Drazzilb08** [Servarr/Wiki#2]
https://wiki.servarr.com/Definitions
List of commonly asked definitions. 
Suggest reaching out to the community to see what other terms should be defined for new users
- [X] Proper
- [X] Repack
- [x] Video quality 
- [x] Audio quality
- [x] Torrents
- [x] Usenet
- [x] Indexers
- [x] Trackers
- [x] Ratio
- [x] Seeders
- [x] Leechers
- [x] Seedboxes

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Definitions

**Comment by Drazzilb08** [comment]
Updates list of definitions to possibly include. Also could look at the community to see what kind of list they'd be looking for to help new users

**Comment by Drazzilb08** [comment]
Updated definitions page added some commonly used words around in our communities.

**Comment by Drazzilb08** [comment]
Added new header `Download Protocols`
- [ ] Usenet
- [ ] Torrents

**Comment by Drazzilb08** [comment]
Included new header `Indexers/Trackers`
- [ ] Indexers
- [ ] Trackers
- [ ] Seeders
- [ ] Leechers
