### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by brixazure** [Servarr/Wiki#201]
I have a log filled with these errors.  and idk why it shows them. I just resolved an issue with a root folder missing. any ideas or do i need to redo the database?
![image](https://user-images.githubusercontent.com/38088897/217889196-f6a1569d-a183-4a49-ae84-6fd19540b061.png)

[AB#4890](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4890)

**Comment by bakerboy448** [comment]
the wiki github is not for support issues.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
