### ISSUE TITLE
Library Isn't Updating Correctly

### ISSUE THREAD

**Issue by JamesSSmith** [Servarr/Wiki#205]
Hello,

So, my drive that had everything on got corrupted, and thus everything has been deleted, so i replaced everything with new drives and created the exact same locations that everything is set to in Radarr, however the content on radarr is not updating to show that the files no longer exist, anyways to force it todo this

![image](https://user-images.githubusercontent.com/58558949/224504486-f5b136a4-034f-450d-9144-122d22bd8300.png)
![image](https://user-images.githubusercontent.com/58558949/224504511-aaf27518-882d-4e48-b856-abe564612e70.png)

these images show that there is nothing in the folder, and the location is the same but the file "still exists" on Radarr

[AB#4902](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4902)

**Comment by bakerboy448** [comment]
The wiki GitHub is not for support
