### ISSUE TITLE
Issue Adding Most but not all Indexers

### ISSUE THREAD

**Issue by AshleyCurtis** [Servarr/Wiki#216]
I get the message: 

Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. The SSL connection could not be established, see inner exception.

IPv6 is disabled, not sure what else to check

**Comment by augustuen** [comment]
This repo is for the Servarr wiki, not any of the Arrs apps. Please use the appropriate support channel (Reddit or Discord) for support.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
