### ISSUE TITLE
JSON Support from Indexers

### ISSUE THREAD

**Issue by braindonors** [Servarr/Wiki#226]
I was trying to add an indexer (nzbindex) that emits JSON rather than XML, is there a plan or path to allow JSON to be accepted from those types of APIs?

**Comment by bakerboy448** [comment]
Servarr
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

====

Sonarr
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
