### ISSUE TITLE
Radarr - Queue view when sorting by column 'Size' does not sort correctly by value

### ISSUE THREAD

**Issue by Grant1ey** [Servarr/Wiki#227]
See image 
![Web capture_14-6-2023_72127_192 168 23 134](https://github.com/Servarr/Wiki/assets/5253274/1c71ec69-c975-46a9-b617-9e37d1b36261)

**Comment by bakerboy448** [comment]
The wiki's GitHub has nothing to do with radarr support issues

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
