### ISSUE TITLE
[Feature Request] Sonarr type app for youtube subscriptions

### ISSUE THREAD

**Issue by anthony0030** [Servarr/Wiki#254]
It would be nice to have an app that downloads videos from youtube and stores/renames them like Sonnar.

**Comment by bakerboy448** [comment]
this has nothing to do with the Servarr wiki

**Comment by anthony0030** [comment]
If I posted this in the wrong repo. what is the correct repo to post it?

**Comment by bakerboy448** [comment]
There is no repo for requesting random apps.

find or pay someone(s) who can build an app
