### ISSUE TITLE
Template:Getting Started

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#3]
https://wiki.servarr.com/Template:Getting_Started

Template:Installation needs a full rework of the processes....

Note: Sonarr is via mono; everything else /should/ not need mono for starting

**Comment by bakerboy448** [comment]
incorporate setup guide into installation https://github.com/Radarr/Radarr/wiki/Setup-Guide

**Comment by bakerboy448** [comment]
also cover installation

**Comment by Drazzilb08** [comment]
Getting started has been moved to Quick Start guide.
