### ISSUE TITLE
corsaro nero new link

### ISSUE THREAD

**Issue by IoSonoAndreaZ** [Servarr/Wiki#315]
at the moment the link configured in Prowlarr is not working, the working one is https://www.ilcorsaronero.info/
Is it possible to add it in prowlarr? Or even better, to make it editable so we can track the frequent link change.
Thanks,
A.

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.

Definition issues can be reported to Prowlarr/Prowlarr for C#; Prowlarr/Indexers or Jackett/Jackett for Cardigann
