### ISSUE TITLE
Non-documentation loop for download clients

### ISSUE THREAD

**Issue by LTangaF** [Servarr/Wiki#322]
https://wiki.servarr.com/radarr/settings#download-clients has a link [More Info (Supported)](https://wiki.servarr.com/radarr/supported#download-clients) where each download client listed has a link [Refer to the Settings Page](https://wiki.servarr.com/radarr/settings#download-clients) that leads back to the first page.

No actual documentation for configuring the clients is provided.

**Comment by bakerboy448** [comment]
Settings page covers the settings and details
Supported page covers the supported clients and sometimes some nuances.

PRs welcome.
