### ISSUE TITLE
Consider adding qbittorrent-nox to the script

### ISSUE THREAD

**Issue by luckygreen** [Servarr/Wiki#369]
Please consider adding qbittorrent-nox (the web GUI version) to the installation script.

A BT client is the one necessary component that the user currently has to install by hand.  My experience, which I suspect is pretty typical for a newcomer to the stack, was to install Radarr from the script, then going to the Trash guides for the qbittorrent installation tips, and then try to figure out how to make what the script does mesh with the Trash instruction. Which is both tedious and human error-prone. In fact, I am about to re-install qbittorrent to make the installation more like how your script installs the other apps.

The script could install qbittorrent-nox as service the same way the other apps get installed, while ensuring that the permissions match, which would be quite helpful.

Thank you tremendously for this awesome script!!!

**Comment by Roxedus** [comment]
qbittorrent is not a servarr application.

**Comment by luckygreen** [comment]
@bakerboy448, allow me to rephrase the question.

If you were handed a PR that adds qbittorrent as a menu item to the script, would you reject the PR?

I am purely motivated by a desire to reduce the pain and needless friction that new users currently have to go through, wasting time and effort, by what could be automated with ease, given the excellent script that you have already written. Thank you for your consideration.

**Comment by Roxedus** [comment]
Yes, The script in this repo is only for Servarr applications, as you can see by the lack of Sonarr in the list.

**Comment by bakerboy448** [comment]
Sonarr in particular has their own install script and thus gets install docs being as part of Starr.

qbit, bazarr or anything that is not Sonarr or Servarr does not belong in the wiki and will always be removed or not merged for PRs
