### ISSUE TITLE
Reduced motion settings not taken into account

### ISSUE THREAD

**Issue by Arteneko** [Servarr/Wiki#374]
Hi! on the wiki page, clicking an in-page link (the table of contents, for example) produces a very slow and animated scrolling animation which completely disregards the user's reduced motion settings.
i need this setting for obvious medical reasons, and such sites then become completely exclusionary because of custom scrolling behaviour that doesn't respect accessibility settings.

Could you make sure to not enable those animations unless the user doesn't have reduced motion settings? Thanks

**Comment by bakerboy448** [comment]
This would be an issue to raise with wikijs

**Comment by Arteneko** [comment]
Well, i'm not the user of wikijs

**Comment by Roxedus** [comment]
Hello. There unfortunately there isn't much servarr can do about that, as this wiki is powered by https://github.com/requarks/wiki, which is where this accessibility issue should be solved.

All the content of the servarr wiki is in this repository, if GitHub is better to navigate.

**Comment by CouldBeThis** [comment]
https://github.com/requarks/wiki/discussions/7594

**Comment by CouldBeThis** [comment]
per the above wikijs issue:

> This will be fixed in v3.
