### ISSUE TITLE
[Installation Script] Provide the option to install Whisparr V3

### ISSUE THREAD

**Issue by damnsanga** [Servarr/Wiki#387]
Currently the Servarr community installation script only installs Whisparr V2.

Can the script please be updated to provide the option to install either V2 or V3 ?

Thank you

**Comment by bakerboy448** [comment]
https://github.com/Servarr/Wiki/edit/master/servarr/servarr-install-script.sh#L102

**Comment by damnsanga** [comment]
Hi Bakerboy,

Does that mean the request has been implemented to update the script, or it will be implemented at some stage?

I just ran the script again and it still installs V2 only

**Comment by damnsanga** [comment]
![image](https://github.com/user-attachments/assets/f8bfea68-91b0-4878-90d8-a563c40e02ba)
I followed the instructions and copied/pasted from https://wiki.servarr.com/install-script

I've attached a screenshot of the CLI output. I don't have the option for V3

Cheers

**Comment by damnsanga** [comment]
I think I have found an issue with the select statement on Line #71, whisparr-v3 had not been assigned and therefore was not shown in the case statement.

![image](https://github.com/user-attachments/assets/70f6c4e5-c370-4f83-ac0e-20ec14be5ed9)

ie, `select app in lidarr prowlarr radarr readarr whisparr whisparr-v3 quit; do`

Thank you

**Comment by bakerboy448** [comment]
Fixed; thanks
