### ISSUE TITLE
Docker Guide

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#67]
https://wiki.servarr.com/Docker_Guide

**Comment by bakerboy448** [comment]
Ready for @fryfrog's QC

**Comment by Drazzilb08** [comment]
I spoke with @fryfrog today in regards to adding a section with respects to testing Hardlinks and the commands that are needed to make that happen.

**Comment by fryfrog** [comment]
I've pointed the reddit wiki at the new wiki. Reviewed the new wiki. Added a section on verifying hard link commands for Linux, will figure out Windows version. Yay!
