### ISSUE TITLE
Radarr - Settings

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#72]
https://wiki.servarr.com/Radarr_Settings

- [x] Media Management
- [x] Profiles
- [x] Quality
- [x] Custom Formats
- [x] Indexers
- [x] Download Clients
- [x] Connect
- [x] Meta Data
- [x] Tags
- [x] General
- [x] UI

**Comment by bakerboy448** [comment]
Ensure #1  is captured

**Comment by bakerboy448** [comment]
Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by bakerboy448** [comment]
Custom Formats Import/Export coming soon

**Comment by Drazzilb08** [comment]
> Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

I feel that something like this might not best fit in the **Settings** page. More towards a documentations page for deeper information more towards a Dev and not a general user.

> Custom Formats Import/Export coming soon

Custom formats added along with Imports/Exports
The section still needs a write up.
