### ISSUE TITLE
Sonarr - Settings

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#73]
https://wiki.servarr.com/Sonarr_Settings
- [x] Media Management
- [x] Profiles
- [x] Quality
- [x] Indexers
- [x] Download Clients
- [x] Connect
- [x] Meta Data
- [x] Tags
- [x] General
- [x] UI

**Comment by bakerboy448** [comment]
Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by bakerboy448** [comment]
1.1.3 Importing needs to explain hard links / when they can be used and not just link to docker

**Comment by bakerboy448** [comment]
List functionality has been added today

**Comment by Drazzilb08** [comment]
> Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

I feel this would be better suited to a programs documentation page and not a general overview of the settings.

> List functionality has been added today
Added
Still needs write up

>1.1.3 Importing needs to explain hard links / when they can be used and not just link to docker
I have no expertise outside of docker and very little Linux knowledge (just found out what a hardline was a couple months ago)
Need somebody with more knowledge
