### ISSUE TITLE
Readarr - Settings

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#74]
https://wiki.servarr.com/Readarr_Settings
- [x] Media Management
- [x] Profiles
- [ ] Quality
- [ ] Indexers
- [ ] Download Clients
- [ ] Connect
- [ ] Meta Data
- [ ] Tags
- [ ] General
- [ ] UI

**Comment by bakerboy448** [comment]
Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by Drazzilb08** [comment]
Readarr's Setting Shell completed
Please see WikiTrackeer to make edits.

> Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

Needs to be put in application documentation and not a general settings overview
