### ISSUE TITLE
Lidarr - Settings

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#75]
https://wiki.servarr.com/Lidarr_Settings
- [x] Media Management
- [x] Profiles
- [x] Quality
- [x] Indexers
- [x] Download Clients
- [x] Connect
- [x] Meta Data
- [x] Tags
- [x] General
- [x] UI

**Comment by bakerboy448** [comment]
Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by Drazzilb08** [comment]
Lidarr's Settings Shell completed
Please see WikiTracker to make appropriate edits.

> Possibly include https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

No.......
