### ISSUE TITLE
Template:Settings Profiles Delay Profiles

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#78]
https://wiki.servarr.com/Template:Settings_Profiles_Delay_Profiles

- [x] Need to fix the tags link

**Comment by bakerboy448** [comment]
the tags link is "Template:Settings_Profiles_Delay_Profiles#Tags"  once in the ARRS we don't want it to link bank to the template; will need to make this link to the arr settings and that bookmark

**Comment by Drazzilb08** [comment]
This is only true when viewing it on the "Template:" page retest on settings page.

**Comment by bakerboy448** [comment]
confirmed

**Comment by Drazzilb08** [comment]
Reopening issue as examples were found that should be in the wiki from https://nzbdrone.readthedocs.io/Delay-Profiles/
extra Vars have been used.

**Comment by bakerboy448** [comment]
add descriptions to the template data variables @Drazzilb08

**Comment by Drazzilb08** [comment]
added variable descriptions

**Comment by bakerboy448** [comment]
made minor updates; looks good
