### ISSUE TITLE
Radarr System

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#80]
https://wiki.servarr.com/Radarr_System
- [x] Status
- [x] Tasks
- [x] Backup
- [x] Updates
- [x] Events
- [x] Log Files

**Comment by bakerboy448** [comment]
Won't be used; System will be at ARR level

**Comment by bakerboy448** [comment]
possibly use like Settings intended (store 'mini templates' in sections here once new extension installed?

**Comment by Drazzilb08** [comment]
After review I see no reason why all of system couldn't entirely be a template,  no need for specific or even sub templates

**Comment by Drazzilb08** [comment]
Systems have been separated between ARR and are no longer a template
