### ISSUE TITLE
Template:Troubleshooting

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#9]
https://wiki.servarr.com/Template:Troubleshooting
**Asking for Help**
- [x] Remove mono comment or make sonarr only?
- [x] Add to mention if on docker that common issues are XXXX and point to docker guide
- [x] Add bookmark to logging and log files
- [x] can we create a discord and/or reddit 'issue' template?

**Logging and Log Files**
- [x]   fix Appdata Directory Link

**Recovering from a Failed Update**
- [x] Determine the issue | fix logging and log files bookmark 
- [x] Migration Issue formatting

**Comment by bakerboy448** [comment]
do we merge Downloading (#4) into this?

**Comment by bakerboy448** [comment]
Generally needs reformatting.

need to fix Appdata Directory Link

**Comment by Drazzilb08** [comment]
> do we merge Downloading (#4) into this?

Yes that is the plan for this

**Comment by bakerboy448** [comment]
added template params
