### ISSUE TITLE
Sonarr Tips and Tricks

### ISSUE THREAD

**Issue by bakerboy448** [Servarr/Wiki#90]
https://wiki.servarr.com/Sonarr_Tips_and_Tricks

**Comment by bakerboy448** [comment]
Include/Embed? see #106 
https://github.com/TRaSH-/Tutorials-FAQ/tree/master/SonarrV3

**Comment by Drazzilb08** [comment]
discord user BitHawkGaming contributed (Converting DB paths from Windows to Linux)

**Comment by bakerboy448** [comment]
need to add this to tips and trips for "unable to load manual import items" https://support.plesk.com/hc/en-us/articles/115000170354-An-operation-or-a-script-that-takes-more-than-60-seconds-to-complete-fails-on-a-website-hosted-in-Plesk-nginx-504-Gateway-Time-out

**Comment by bakerboy448** [comment]
https://www.reddit.com/r/sonarr/comments/iy6zvo/x265_preferred/g6b8wuy/

**Comment by Drazzilb08** [comment]
https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts
